version: "3.8"

services:
  nest-app:
    build: .
    env_file:
      - .env
    environment:
    #   - PORT=4000
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    #   - DATABASE_USER=postgres
    #   - DATABASE_PASSWORD=password
      - REDIS_HOST=redis
    #   - REDIS_PORT=6379
    #   - REDIS_PASSWORD=password
    #   - SWAGGER_ENABLED=true
      - DATABASE_SYNCHRONIZE=true
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
